name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyinstaller

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.28.3'

      - name: Install pybind11
        run: |
          pip install pybind11
          echo "PYBIND11_DIR=$(python -m pybind11 --cmakedir)" >> $GITHUB_ENV

      - name: Build DLL
        run: |
          cmake -S dll_lib -B build -DCMAKE_BUILD_TYPE=Release -Dpybind11_DIR="$PYBIND11_DIR"
          cmake --build build --config Release

      - name: Build GUI app
        run: |
          pyinstaller examples/example_ui.py --noconfirm --onefile --windowed --name=example_ui

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            build/*.dll
            dist/example_ui*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-artifacts/**/*.dll
            release-artifacts/**/example_ui*
