name: Build and Release WT9011 DLL

on:
  push:
    tags:
      - 'v*.*.*' # Запуск при пуше тега вроде v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        & "$env:pythonLocation\python.exe" -m pip install --upgrade pip
        & "$env:pythonLocation\python.exe" -m pip install pybind11 bleak
      shell: pwsh

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.22.x'

    - name: Create build directory and build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ../dll_lib || cmake -G "Visual Studio 16 2019" -A x64 ../dll_lib
        cmake --build . --config Release
      shell: pwsh

    - name: Copy Python files to lib directory
      run: |
        mkdir build\Release\lib
        copy lib\*.py build\Release\lib\
      shell: pwsh

    - name: Package release
      run: |
        cd build\Release
        7z a wt9011_release.zip wt9011_dll.dll lib\*.py
      shell: pwsh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/Release/wt9011_release.zip
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
