name: Build and Release WT9011 DLL

on:
  push:
    tags:
      - 'v*.*.*' # Триггер на теги вроде v1.0.0

jobs:
  build:
    runs-on: windows-latest # Используем Windows для сборки DLL

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # Укажите нужную версию Python

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11 bleak

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.20.x'

    - name: Create build directory and build
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release

    - name: Copy Python files to lib directory
      run: |
        mkdir build\Release\lib
        copy lib\*.py build\Release\lib\

    - name: Package release
      run: |
        cd build\Release
        7z a wt9011_release.zip wt9011_dll.dll lib\*.py

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/Release/wt9011_release.zip
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}