name: Build Windows Executable

on:
  push:
    tags:
      - 'app_v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python setup — чистый venv
      - name: Set up Python and install packages
        shell: cmd
        run: |
          python -m venv venv
          venv\Scripts\python.exe -m pip install --upgrade pip
          venv\Scripts\python.exe -m pip install bleak pyqt5

      # Установка MSYS2 и инструментов сборки
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-toolchain

      # Копирование файлов
      - name: Copy Python files to build/
        run: |
          mkdir build
          copy *.py build

      # Сборка с qmake
      - name: Build with qmake
        shell: msys2 {0}
        run: |
          cd examples/app
          /mingw64/bin/qmake wt9011_app.pro
          mingw32-make -j$(nproc)

      # Подготовка релиза
      - name: Prepare release
        shell: msys2 {0}
        run: |
          mkdir -p release
          cp build/release/wt9011_app.exe release/
          cp *.py release/
          /mingw64/bin/windeployqt release/wt9011_app.exe
          cp /mingw64/bin/libgcc_s_seh-1.dll release/
          cp /mingw64/bin/libstdc++-6.dll release/
          cp /mingw64/bin/libwinpthread-1.dll release/

      # Копирование Python зависимостей
      - name: Copy Python site-packages
        run: |
          xcopy /E /I venv\Lib\site-packages release\site-packages

      # Архивация
      - name: Zip release
        run: |
          7z a wt9011_app_${{ github.ref_name }}.zip .\release\*

      # Загрузка артефакта
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wt9011_app_${{ github.ref_name }}
          path: wt9011_app_${{ github.ref_name }}.zip
