name: Build DLL and PyQt App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 pyqt5 pyinstaller

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y qtbase5-dev cmake build-essential ninja-build

      - name: Install system deps (macOS)
        if: runner.os == 'macOS'
        run: brew install qt cmake ninja

      - name: Install system deps (Windows)
        if: runner.os == 'Windows'
        run: choco install -y cmake ninja python qt5

      - name: Build DLL with embedded Python
        run: |
          cmake -S dll_lib -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Build PyQt GUI App with PyInstaller
        run: |
          pyinstaller examples/example_ui.py --onefile --name example_ui

      - name: Prepare artifacts
        run: |
          mkdir -p output
          cp build/*wt9011lib* output/ || true
          cp dist/example_ui* output/ || true

      - uses: actions/upload-artifact@v4
        with:
          name: wt9011-${{ runner.os }}
          path: output/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip artifacts by platform
        run: |
          cd artifacts
          for dir in *; do zip -r "../${dir}.zip" "$dir"; done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip
